### ISSUE TITLE
Contrast setting switch would be nice (feauture request)

### ISSUE THREAD

**Issue by cantcodetho** [Fidifis/TextureMerge#6]
So when I combine gray textures to make lets say a pack of grunge textures in channels, it would be nice to have AUTO max contrast switch and perhaps also invert texture (negative) per channel.

When I pack grunge textures intended to be used with channel selection it is annoying to have them at different brightness/contrast. So I still do this in Photoshop because I simply hit ctrl+shift+alt+L and I get instant auto max contrast. Very useful feature.

**Comment by Fidifis** [comment]
You will now find this feature in v1.4.0
It is located in the Actions dropdown as a Auto Levels.

If we misunderstood and you had a different functioning in mind, feel free to reopen this issue.

https://github.com/Fidifis/TextureMerge/releases/tag/v1.4.0
